FROM python:3.11-bookworm

COPY /app /app
WORKDIR /app
RUN rm -rf saves/ __pycache__/ data/
RUN pip3 install --upgrade pip
RUN pip3 install  torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
RUN pip3 install tqdm matplotlib scikit-learn pandas